name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Forge Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.7.1

      - name: Show Forge version
        run: forge --version

      - name: Run forge fmt
        run: forge fmt --check

      - name: Run forge build
        run: forge build --sizes

      - name: Run forge tests
        run: forge test -vvv
